# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Spaetzel
email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnspaetzel.com"

plugins:
  - jekyll-sitemap

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:slug

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
