name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      #- run: bundle install
      #- run: bundle exec jekyll build
      - run: mkdir _site
      - run: touch _site/test
      - run: git clone "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      - run: cd $(basename ${GITHUB_REPOSITORY})
      - run: pwd
      - run: git config user.name "Gitub Actions"
      - run: git config user.email ""
      - run: rsync -avz --delete --exclude '.git*' ${GITHUB_WORKSPACE}/_site/ .
      - run: touch .nojekyll
      - run: git add -A .
      - run: git commit -m "Generated Jekyll site by Github Action - ${GITHUB_ACTION}"
      - run: git status
      - run: ls
      # - run: git push --force "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" HEAD:gh-pages
